apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: us-central1-docker.pkg.dev/winged-app-477017-r9/quicklunch/store-service-dev:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer