apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quicklunch-dev
  name: store-service-config
  labels:
    app: 'store-service'
data:
  DEFAULT_STORE: | 
    {
      "id": 1024,
      "name": "Sunshine Cafe",
      "cityId": 33,
      "cityName": "Berlin",
      "lon": "13.4050",
      "lat": "52.5200",
      "phone": "+49 30 12345678",
      "email": "contact@sunshinecafe.de",
      "address": "Alexanderplatz 5, 10178 Berlin, Germany"
    }
  DEFAULT_COUNRTY: Germany
  
