apiVersion: v1
kind: Service
metadata:
  namespace: quicklunch-dev
  name: store-service
spec:
  type: ClusterIP
  selector:
    app: store-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP